### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by emlyn** [qubole/sparklens#2]
I had a run crash with the following stacktrace (IIUC caused by a job with no stages?) causing my spark app to fail:
```
java.lang.UnsupportedOperationException: empty.max
	at scala.collection.TraversableOnce$class.max(TraversableOnce.scala:229)
	at scala.collection.AbstractTraversable.max(Traversable.scala:104)
	at com.qubole.sparklens.timespan.JobTimeSpan.computeCriticalTimeForJob(JobTimeSpan.scala:52)
	at com.qubole.sparklens.analyzer.EfficiencyStatisticsAnalyzer$$anonfun$4.apply(EfficiencyStatisticsAnalyzer.scala:62)
	at com.qubole.sparklens.analyzer.EfficiencyStatisticsAnalyzer$$anonfun$4.apply(EfficiencyStatisticsAnalyzer.scala:62)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.qubole.sparklens.analyzer.EfficiencyStatisticsAnalyzer.analyze(EfficiencyStatisticsAnalyzer.scala:62)
	at com.qubole.sparklens.analyzer.AppAnalyzer$class.analyze(AppAnalyzer.scala:30)
	at com.qubole.sparklens.analyzer.EfficiencyStatisticsAnalyzer.analyze(EfficiencyStatisticsAnalyzer.scala:26)
	at com.qubole.sparklens.QuboleJobListener$$anonfun$onApplicationEnd$3.apply(QuboleJobListener.scala:159)
	at com.qubole.sparklens.QuboleJobListener$$anonfun$onApplicationEnd$3.apply(QuboleJobListener.scala:158)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
	at com.qubole.sparklens.QuboleJobListener.onApplicationEnd(QuboleJobListener.scala:158)
	at org.apache.spark.scheduler.SparkListenerBus$class.doPostEvent(SparkListenerBus.scala:57)
	at org.apache.spark.scheduler.LiveListenerBus.doPostEvent(LiveListenerBus.scala:36)
	at org.apache.spark.scheduler.LiveListenerBus.doPostEvent(LiveListenerBus.scala:36)
	at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:63)
	at org.apache.spark.scheduler.LiveListenerBus.postToAll(LiveListenerBus.scala:36)
	at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(LiveListenerBus.scala:94)
	at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(LiveListenerBus.scala:79)
	at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(LiveListenerBus.scala:79)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1.apply$mcV$sp(LiveListenerBus.scala:78)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1279)
	at org.apache.spark.scheduler.LiveListenerBus$$anon$1.run(LiveListenerBus.scala:77)
```

**Comment by emlyn** [comment]
I changed `computeCriticalTimeForJob` to: 
```scala
  def computeCriticalTimeForJob(): Long = {
    if (stageMap.isEmpty) {
      0
    } else {
      val maxStageID = stageMap.map(x => x._1).max
      val data  = stageMap.map(x =>
        ( x._1,
          (
            x._2.parentStageIDs,
            x._2.stageMetrics.map(AggregateMetrics.executorRuntime).max
          )
        )
      )
      criticalTime(maxStageID, data)
    }
  }
```
which seems to work around it, but not sure if it's the best fix (or if there's a more idiomatic way to do that).

**Comment by iamrohit** [comment]
Thanks @emlyn!
Just pushed your fix. Also added protection for unseen failures.
