### ISSUE TITLE
The qubole#sparklens;0.3.2-s_2.11 module is intermittently not found in the SparkPackages repo

### ISSUE THREAD

**Issue by jeffkpayne** [qubole/sparklens#65]
According to https://mvnrepository.com/artifact/qubole/sparklens/0.3.2-s_2.11, the module should be available in SparkPackages, but we've seen intermittent download failures over the past week or so.  For instance, right now, the package is not available.  It looks like potentially an issue with https://dl.bintray.com/, as all requests are getting a `403 Forbidden` response.  Do you have any plans to host the module on a different maven repo?

**Comment by suryadevarauday** [comment]
Same here getting 

:: problems summary ::
:::: WARNINGS
		module not found: qubole#sparklens;0.3.0-s_2.11
==== central: tried
	  https://repo1.maven.org/maven2/qubole/sparklens/0.3.0-s_2.11/sparklens-0.3.0-s_2.11.pom
	  -- artifact qubole#sparklens;0.3.0-s_2.11!sparklens.jar:
	  https://repo1.maven.org/maven2/qubole/sparklens/0.3.0-s_2.11/sparklens-0.3.0-s_2.11.jar
	==== spark-packages: tried
	  https://dl.bintray.com/spark-packages/maven/qubole/sparklens/0.3.0-s_2.11/sparklens-0.3.0-s_2.11.pom
	  -- artifact qubole#sparklens;0.3.0-s_2.11!sparklens.jar:
	  https://dl.bintray.com/spark-packages/maven/qubole/sparklens/0.3.0-s_2.11/sparklens-0.3.0-s_2.11.jar
		::::::::::::::::::::::::::::::::::::::::::::::
		::          UNRESOLVED DEPENDENCIES         ::
		::::::::::::::::::::::::::::::::::::::::::::::
		:: qubole#sparklens;0.3.0-s_2.11: not found
		::::::::::::::::::::::::::::::::::::::::::::::

**Comment by ishansrivastava** [comment]
./bin/spark-submit --packages qubole:sparklens:0.3.2-s_2.11 --class com.qubole.sparklens.app.ReporterApp qubole-dummy-arg <filename> source=history

On running the above command i am getting an error :"Exception in thread "main" org.apache.spark.SparkException: Master must either be yarn or start with spark, mesos, k8s, or local".

So is it possible that this error is due to this issue #65 itself?

**Comment by hoaihuongbk** [comment]
Same you, just try today

**Comment by chicago58** [comment]
the same to me.

:: problems summary ::
:::: WARNINGS
                module not found: qubole#Sparklens;0.3.1-s_2.11

        ==== local-m2-cache: tried

          file:/data/daojia_mall/.m2/repository/qubole/Sparklens/0.3.1-s_2.11/Sparklens-0.3.1-s_2.11.pom

          -- artifact qubole#Sparklens;0.3.1-s_2.11!Sparklens.jar:

          file:/data/daojia_mall/.m2/repository/qubole/Sparklens/0.3.1-s_2.11/Sparklens-0.3.1-s_2.11.jar

        ==== local-ivy-cache: tried

          /data/daojia_mall/.ivy2/local/qubole/Sparklens/0.3.1-s_2.11/ivys/ivy.xml

          -- artifact qubole#Sparklens;0.3.1-s_2.11!Sparklens.jar:

          /data/daojia_mall/.ivy2/local/qubole/Sparklens/0.3.1-s_2.11/jars/Sparklens.jar

        ==== central: tried

          https://repo1.maven.org/maven2/qubole/Sparklens/0.3.1-s_2.11/Sparklens-0.3.1-s_2.11.pom

          -- artifact qubole#Sparklens;0.3.1-s_2.11!Sparklens.jar:

          https://repo1.maven.org/maven2/qubole/Sparklens/0.3.1-s_2.11/Sparklens-0.3.1-s_2.11.jar

        ==== spark-packages: tried

          http://dl.bintray.com/spark-packages/maven/qubole/Sparklens/0.3.1-s_2.11/Sparklens-0.3.1-s_2.11.pom

          -- artifact qubole#Sparklens;0.3.1-s_2.11!Sparklens.jar:

          http://dl.bintray.com/spark-packages/maven/qubole/Sparklens/0.3.1-s_2.11/Sparklens-0.3.1-s_2.11.jar

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: qubole#Sparklens;0.3.1-s_2.11: not found

                ::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: qubole#Sparklens;0.3.1-s_2.11: not found]
        at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1308)
        at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:54)
        at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:315)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:143)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:926)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:935)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by Kwafoor** [comment]
<repository>
      <id>bintray</id>
      <name>bintray.com</name>
      <url>https://repos.spark-packages.org</url>
    </repository>

this repository should work.

**Comment by beryllw** [comment]
```
<repository>
      <id>bintray</id>
      <name>bintray.com</name>
      <url>https://repos.spark-packages.org</url>
    </repository>
```
this should work

**Comment by kommuembroker** [comment]
where should you add  @Kwafoor ?

[](<repository>
      <id>bintray</id>
      <name>bintray.com</name>
      <url>https://repos.spark-packages.org</url>
    </repository>)
